spring:
  application:
    name: FortuneCookie
  #database ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: qwer4321!
  #h2 ??
  h2:
    console:
      path: /h2-console
      enabled: true

